### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by Zanacci** [R6Stats/discord-bot#8]
The bot runs but I get this error and no commands are working.

`(node:12016) UnhandledPromiseRejectionWarning: Error: Unknown authentication error occurred
    at R6StatsAPI.authenticate (C:\Users\Youn\Desktop\dokkaebi\discord-bot-master\node_modules\r6stats\dist\R6StatsAPI.js:74:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This is what my config file looks like

`module.exports = {
	r6stats: {
		login: 'uplay email',
		password: 'uplay password',
    user_agent: 'Dokkaebi',
    base_url: 'https://api.r6stats.com/api/v1',
	},
	discord: {
		token: 'BOT TOKEN',
	},
}`

Not sure what to do, help is really appreciated, thanks.

**Comment by Mann-o** [comment]
That package and API URL have been deprecated for quite some time now. If you would like access to our new API please let me know your R6Stats username (the one you registered to R6Stats with, not your UPlay username).

Please reach out to me (Manno) on Discord and we'll get you sorted with an API key for our new API.
